development:
 access_key_id: YOUR_ID
 secret_access_key: YOUR_SECRET_KEY
 bucket: BUCKET_NAME
 s3_host_name: s3-ap-northeast-1.amazonaws.com
production:
 access_key_id: YOUR_ID
 secret_access_key: YOUR_SECRET_KEY
 bucket: BUCKET_NAME
 s3_host_name: s3-ap-northeast-1.amazonaws.com