# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20120411040030) do

  create_table "active_admin_comments", :force => true do |t|
    t.integer  "resource_id",   :null => false
    t.string   "resource_type", :null => false
    t.integer  "author_id"
    t.string   "author_type"
    t.text     "body"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "namespace"
  end

  add_index "active_admin_comments", ["author_type", "author_id"], :name => "index_active_admin_comments_on_author_type_and_author_id"
  add_index "active_admin_comments", ["namespace"], :name => "index_active_admin_comments_on_namespace"
  add_index "active_admin_comments", ["resource_type", "resource_id"], :name => "index_admin_notes_on_resource_type_and_resource_id"

  create_table "admin_users", :force => true do |t|
    t.string   "email",                  :default => "", :null => false
    t.string   "encrypted_password",     :default => "", :null => false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          :default => 0
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "admin_users", ["email"], :name => "index_admin_users_on_email", :unique => true
  add_index "admin_users", ["reset_password_token"], :name => "index_admin_users_on_reset_password_token", :unique => true

  create_table "caretakers", :force => true do |t|
    t.string   "name"
    t.string   "div_name"
    t.string   "person"
    t.string   "person_yomi"
    t.string   "addr"
    t.string   "email"
    t.string   "tel"
    t.string   "fax"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "ext_id"
    t.integer  "note_id"
    t.string   "zipcode"
  end

  create_table "headers", :force => true do |t|
    t.string   "name"
    t.string   "label_name"
    t.string   "desc_name"
    t.boolean  "active_name"
    t.string   "example_name"
    t.string   "label_yomi"
    t.string   "desc_yomi"
    t.boolean  "active_yomi"
    t.string   "example_yomi"
    t.string   "label_pref"
    t.string   "desc_pref"
    t.boolean  "active_pref"
    t.string   "example_pref"
    t.string   "label_city"
    t.string   "desc_city"
    t.boolean  "active_city"
    t.string   "example_city"
    t.string   "label_addr"
    t.string   "desc_addr"
    t.boolean  "active_addr"
    t.string   "example_addr"
    t.string   "label_zipcode"
    t.string   "desc_zipcode"
    t.boolean  "active_zipcode"
    t.string   "example_zipcode"
    t.string   "label_build_name"
    t.string   "desc_build_name"
    t.boolean  "active_build_name"
    t.string   "example_build_name"
    t.string   "label_tel"
    t.string   "desc_tel"
    t.boolean  "active_tel"
    t.string   "example_tel"
    t.string   "label_lat_256jp"
    t.string   "desc_lat_256jp"
    t.boolean  "active_lat_256jp"
    t.string   "example_lat_256jp"
    t.string   "label_lng_256jp"
    t.string   "desc_lng_256jp"
    t.boolean  "active_lng_256jp"
    t.string   "example_lng_256jp"
    t.string   "label_lat_world"
    t.string   "desc_lat_world"
    t.boolean  "active_lat_world"
    t.string   "example_lat_world"
    t.string   "label_lng_world"
    t.string   "desc_lng_world"
    t.boolean  "active_lng_world"
    t.string   "example_lng_world"
    t.string   "label_hour"
    t.string   "desc_hour"
    t.boolean  "active_hour"
    t.string   "example_hour"
    t.string   "label_holiday"
    t.string   "desc_holiday"
    t.boolean  "active_holiday"
    t.string   "example_holiday"
    t.string   "label_spot_fee"
    t.string   "desc_spot_fee"
    t.boolean  "active_spot_fee"
    t.string   "example_spot_fee"
    t.string   "label_has_park"
    t.string   "desc_has_park"
    t.boolean  "active_has_park"
    t.string   "example_has_park"
    t.string   "label_park_num"
    t.string   "desc_park_num"
    t.boolean  "active_park_num"
    t.string   "example_park_num"
    t.string   "label_park_fee"
    t.string   "desc_park_fee"
    t.boolean  "active_park_fee"
    t.string   "example_park_fee"
    t.string   "label_tollway"
    t.string   "desc_tollway"
    t.boolean  "active_tollway"
    t.string   "example_tollway"
    t.string   "label_url"
    t.string   "desc_url"
    t.boolean  "active_url"
    t.string   "example_url"
    t.string   "label_access_train"
    t.string   "desc_access_train"
    t.boolean  "active_access_train"
    t.string   "example_access_train"
    t.string   "label_access_car"
    t.string   "desc_access_car"
    t.boolean  "active_access_car"
    t.string   "example_access_car"
    t.string   "label_about_title"
    t.string   "desc_about_title"
    t.boolean  "active_about_title"
    t.string   "example_about_title"
    t.string   "label_about_body"
    t.string   "desc_about_body"
    t.boolean  "active_about_body"
    t.string   "example_about_body"
    t.string   "label_info_0"
    t.string   "desc_info_0"
    t.boolean  "active_info_0"
    t.string   "example_info_0"
    t.string   "label_info_1"
    t.string   "desc_info_1"
    t.boolean  "active_info_1"
    t.string   "example_info_1"
    t.string   "label_info_2"
    t.string   "desc_info_2"
    t.boolean  "active_info_2"
    t.string   "example_info_2"
    t.string   "label_info_3"
    t.string   "desc_info_3"
    t.boolean  "active_info_3"
    t.string   "example_info_3"
    t.string   "label_info_4"
    t.string   "desc_info_4"
    t.boolean  "active_info_4"
    t.string   "example_info_4"
    t.string   "label_info_5"
    t.string   "desc_info_5"
    t.boolean  "active_info_5"
    t.string   "example_info_5"
    t.string   "label_info_6"
    t.string   "desc_info_6"
    t.boolean  "active_info_6"
    t.string   "example_info_6"
    t.string   "label_info_7"
    t.string   "desc_info_7"
    t.boolean  "active_info_7"
    t.string   "example_info_7"
    t.string   "label_info_8"
    t.string   "desc_info_8"
    t.boolean  "active_info_8"
    t.string   "example_info_8"
    t.string   "label_info_9"
    t.string   "desc_info_9"
    t.boolean  "active_info_9"
    t.string   "example_info_9"
    t.string   "label_info_10"
    t.string   "desc_info_10"
    t.boolean  "active_info_10"
    t.string   "example_info_10"
    t.string   "label_info_11"
    t.string   "desc_info_11"
    t.boolean  "active_info_11"
    t.string   "example_info_11"
    t.string   "label_info_12"
    t.string   "desc_info_12"
    t.boolean  "active_info_12"
    t.string   "example_info_12"
    t.string   "label_info_13"
    t.string   "desc_info_13"
    t.boolean  "active_info_13"
    t.string   "example_info_13"
    t.string   "label_info_14"
    t.string   "desc_info_14"
    t.boolean  "active_info_14"
    t.string   "example_info_14"
    t.string   "label_photo_file_name"
    t.string   "desc_photo_file_name"
    t.boolean  "active_photo_file_name"
    t.string   "example_photo_file_name"
    t.string   "label_photo_content_type"
    t.string   "desc_photo_content_type"
    t.boolean  "active_photo_content_type"
    t.string   "example_photo_content_type"
    t.string   "label_photo_file_size"
    t.string   "desc_photo_file_size"
    t.boolean  "active_photo_file_size"
    t.string   "example_photo_file_size"
    t.string   "label_checked"
    t.string   "desc_checked"
    t.boolean  "active_checked"
    t.string   "example_checked"
    t.string   "label_caretaker_inputed"
    t.string   "desc_caretaker_inputed"
    t.boolean  "active_caretaker_inputed"
    t.string   "example_caretaker_inputed"
    t.string   "label_user_id"
    t.string   "desc_user_id"
    t.boolean  "active_user_id"
    t.string   "example_user_id"
    t.string   "label_caretaker_id"
    t.string   "desc_caretaker_id"
    t.boolean  "active_caretaker_id"
    t.string   "example_caretaker_id"
    t.string   "label_project_id"
    t.string   "desc_project_id"
    t.boolean  "active_project_id"
    t.string   "example_project_id"
    t.string   "label_note_id"
    t.string   "desc_note_id"
    t.boolean  "active_note_id"
    t.string   "example_note_id"
    t.string   "label_deny"
    t.string   "desc_deny"
    t.boolean  "active_deny"
    t.string   "example_deny"
    t.string   "label_ext_id"
    t.string   "desc_ext_id"
    t.boolean  "active_ext_id"
    t.string   "example_ext_id"
    t.string   "label_linenum"
    t.string   "desc_linenum"
    t.boolean  "active_linenum"
    t.string   "example_linenum"
    t.string   "label_active"
    t.string   "desc_active"
    t.boolean  "active_active"
    t.string   "example_active"
    t.string   "label_gid"
    t.string   "desc_gid"
    t.boolean  "active_gid"
    t.string   "example_gid"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "mst_citycodes", :force => true do |t|
    t.date     "valid_date"
    t.string   "code"
    t.string   "pref"
    t.string   "city"
    t.string   "town"
    t.integer  "city_len"
    t.integer  "town_len"
    t.string   "city_yomi"
    t.string   "town_yomi"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "notes", :force => true do |t|
    t.text     "text"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "projects", :force => true do |t|
    t.string   "name"
    t.string   "client"
    t.integer  "header_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "spots", :force => true do |t|
    t.string   "name"
    t.string   "yomi"
    t.string   "pref"
    t.string   "city"
    t.string   "addr"
    t.string   "zipcode"
    t.string   "build_name"
    t.string   "tel"
    t.integer  "lat_256jp"
    t.integer  "lng_256jp"
    t.float    "lat_world"
    t.float    "lng_world"
    t.string   "hour"
    t.string   "holiday"
    t.string   "spot_fee"
    t.boolean  "has_park"
    t.string   "park_num"
    t.string   "park_fee"
    t.boolean  "tollway"
    t.string   "url"
    t.string   "access_train"
    t.string   "access_car"
    t.string   "about_title"
    t.string   "about_body"
    t.string   "info_0"
    t.string   "info_1"
    t.string   "info_2"
    t.string   "info_3"
    t.string   "info_4"
    t.string   "info_5"
    t.string   "info_6"
    t.string   "info_7"
    t.string   "info_8"
    t.string   "info_9"
    t.string   "info_10"
    t.string   "info_11"
    t.string   "info_12"
    t.string   "info_13"
    t.string   "info_14"
    t.string   "photo_file_name"
    t.string   "photo_content_type"
    t.string   "photo_file_size"
    t.boolean  "checked"
    t.boolean  "caretaker_inputed"
    t.integer  "user_id"
    t.integer  "caretaker_id"
    t.integer  "project_id"
    t.integer  "note_id"
    t.boolean  "deny",               :default => false
    t.string   "ext_id"
    t.integer  "linenum"
    t.boolean  "active"
    t.integer  "gid"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
